# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-11 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coustmer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio_site',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='log',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='name',
            field=models.CharField(default='00', max_length=250),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='password',
            field=models.CharField(default='00', max_length=1000),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='phno',
            field=models.BigIntegerField(default='00'),
        ),
    ]
