# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-16 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coustmer', '0002_auto_20190511_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='username',
            field=models.CharField(default='00', max_length=250),
        ),
    ]
