# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-16 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coustmer', '0003_auto_20190516_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='newc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('log', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
