# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-16 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coustmer', '0004_newc'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='carsp',
            field=models.BigIntegerField(default='00'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='max_cars',
            field=models.BigIntegerField(default='00'),
        ),
    ]
