# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-23 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coustmer', '0005_auto_20190516_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='totalcarsp',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
