# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-23 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coustmer', '0007_auto_20190523_1448'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newc',
        ),
    ]
