# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-25 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coustmer', '0008_delete_newc'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, unique=True)),
                ('password', models.CharField(blank=True, max_length=100, unique=True)),
                ('carno', models.CharField(blank=True, max_length=10, unique=True)),
                ('phno', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
