# Generated by Django 2.1 on 2019-07-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190601_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cctvcode',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='phno',
            field=models.IntegerField(default='0'),
        ),
    ]
