# Generated by Django 2.1 on 2019-07-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190704_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewer',
            name='in_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='viewer',
            name='out_time',
            field=models.IntegerField(),
        ),
    ]
